### PR TITLE
WIP: Begin roadmap for q3 work

### PR DESCRIPTION
**Pull request by ethanfrey**
This is the start of clarifying the mid-term roadmap for q3 (we start End of july, so this goes til end of october, not typicall q3 but "3 months from planning").

I'd like some feedback and discussion so we can get clarity here, which should help make future sprint planning and organization easier.

### CODE REVIEW

**Comment by ruseinov** [comment]
This looks good to me, I'd add a potential tendermint version upgrade after the alphanet launches, but I can see how we might do it later too, because there are going to be breaking changes and maybe issues with tendermint stability.

**Comment by ethanfrey** [comment]
Yeah, let's give them a bit.... seems a bug in 0.23.0....

https://forum.cosmos.network/t/launch-gaia-7002/599/5

**Comment by ethanfrey** [comment]
I'm waiting for a stable testnet from cosmos before upgrade.
Honestly, the bugs in 3 of the last 4 were in cosmos-sdk, this last one in tendermint due to a fix for earlier sdk bug....

**Comment by ethanfrey** [comment]
Okay, I still need to clean this up a bit before I consider it ready for merge. Will try to do that this week.More comments definitely welcome

**Pull request merged**
